# Use a base image with Go and Nakama installed
FROM heroiclabs/nakama-pluginbuilder:3.15.0 AS builder

# Copy the plugin code to the container
WORKDIR /backend
COPY . .

# Build the plugin
RUN go build -buildmode=plugin -trimpath -o ./backend.so

# Use the official Nakama image as the final image
FROM heroiclabs/nakama:3.15.0

# Copy the built plugin to the plugins folder
COPY --from=builder /backend/backend.so /nakama/data/modules

# Expose the ports for Nakama
EXPOSE 7349 7350 7351

# Run Nakama with the specified flags
CMD ["/bin/sh", "-ecx", "/nakama/nakama --name nakama1 --database.address root@cockroachdb:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100"]
